# Site settings
author: Chloe Steffens
title: Software Engineering - A Journey
header-img: img/home-bg.png
email: caforonda103@yahoo.com
copyright_name: Chloe Steffens
description: > # this means to ignore newlines until "baseurl:"
  Chloe's SE Journey
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ohaiklochan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
